# Generated by Django 5.2.10 on 2026-01-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='skills/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(help_text='Enter value between 0 to 100'),
        ),
    ]
